
site_name: WIKI
site_url: https://wiki.amcsui.ir
plugins:
  - section-index
  - search
  - optimize
theme:
  name: material
  language: fa
  palette: 
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/lightbulb-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: custom
      accent: deep purple
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: deep purple
      toggle:
        icon: material/lightbulb-outline
        name: Switch to system preference
  favicon: assets/favicon.ico
  logo: assets/logo.png

extra_css:
  - stylesheets/extra.css